### ISSUE TITLE
Enable Encryption at Rest for Buckets

### ISSUE THREAD

**Issue by cvalaas** [gozer/vertical#7]
https://github.com/gozer/vertical/blob/da2f1d49e556fcb72b73af82026370a4c1b4fdf4/nubis/terraform/main.tf#L216

The bucket holding the backups is not encrypting the files. Probably should?

(I can submit a PR if you want:
1) Either put the bucket code inline here with SSE options, or
2) Modify the "bucket" module to always add SSE, or
3) Create a new "bucket_encrypted" module which includes SSE)

**Comment by gozer** [comment]
Better option still would be to add en encrypted option to the Nubis bucket module and make use of that.

If you look at nubisproject/nubis-terraform/bucket you should see the existing code.

I’d add an encrypted option and default to false.

**Comment by cvalaas** [comment]
Yeah, that would be best, but I don't think terraform supports that. There's no "enabled" option for SSE that I can see:

https://www.terraform.io/docs/providers/aws/r/s3_bucket.html#enable-default-server-side-encryption

**Comment by gozer** [comment]
It’s one of these sub resource blocks

https://www.terraform.io/docs/providers/aws/r/s3_bucket.html#sse_kms_encrypted_objects

And they are always tricky to make optionnal but there is a way.

I’ll take a stab at implementing this tonorrow morning!

**Comment by gozer** [comment]
This feature will be released shortly in Nubis v2.3.0, simply by adding
```
storage_encrypted_at_rest = true
```

To the bucket module invocation
